application: appfoogle
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static_files
  static_dir: static_files

- url: /(index.html)?
  static_files: static_files/index.html
  upload: static_files/index.html

- url: /searchbar.html
  static_files: static_files/searchbar.html
  upload: static_files/searchbar.html

- url: /templatemessage.html
  static_files: static_files/templatemessage.html
  upload: static_files/templatemessage.html

- url: /templatepost.html
  static_files: static_files/templatepost.html
  upload: static_files/templatepost.html

- url: /templatecomment.html
  static_files: static_files/templatecomment.html
  upload: static_files/templatecomment.html

- url: /requests.html
  static_files: static_files/requests.html
  upload: static_files/requests.html

- url: /harry.html
  static_files: static_files/harry.html
  upload: static_files/harry.html

- url: /channel.html
  static_files: static_files/channel.html
  upload: static_files/channel.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

builtins:
- deferred: on
